# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import plotter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=plotter.models.get_image_path)),
            ],
        ),
    ]
